name: Sync DEV to PROD

on:
  push:
    branches:
      - fabric  # Exécuter le workflow à chaque fois que vous poussez sur la branche fabric
    paths:
      - '**'  # Surveiller les changements sur tous les fichiers

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository A
    - name: Checkout repository A
      uses: actions/checkout@v3

    # 2. Configurer Git avec votre nom d'utilisateur et email
    - name: Set up Git
      run: |
        git config --global user.name "ayoubaassou01"
        git config --global user.email "ayoubaassou01@gmail.com"

    # 3. Cloner le dépôt B dans un sous-répertoire
    - name: Clone repository B
      run: |
        git clone https://<github-username>:${{ secrets.PAT_B_TOKEN }}@github.com/<github-username>/PROD.git repoPROD

    # 4. Copier les fichiers du dépôt A dans le dépôt B
    - name: Copy files to repository B
      run: |
        rsync -av --delete ./ repoPROD/  # Copy all files from A to B

    # 5. Pousser les changements dans B
    - name: Commit and push changes to repository B
      working-directory: repoPROD
      run: |
        git add .
        git commit -m "Sync from repository A"
        git push origin PROD  # Vous pouvez ajuster la branche de B si nécessaire
