name: Sync DEV to PROD

on:
  push:
    branches:
      - fabric  # Exécuter le workflow à chaque fois que vous poussez sur la branche fabric
    paths:
      - '**'  # Surveiller les changements sur tous les fichiers

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository A
    - name: Checkout repository A
      uses: actions/checkout@v4

    # 2. Configurer Git avec votre nom d'utilisateur et email
    - name: Set up Git
      run: |
        git config --global user.name "ayoubaassou01"
        git config --global user.email "ayoubaassou01@gmail.com"

    # 3. Cloner le dépôt B dans un sous-répertoire
    - name: Clone repository B
      run: |
        git clone https://github.com/ayoubaassou01/PROD.git
        cd PROD/
        git remote add DEV https://github.com/ayoubaassou01/DEV.git
        git remote update
        git merge fabric/PROD
        git push origin PROD 
