name: Merge Fabric into PROD

on:
  push:
    branches:
      - fabric

permissions:
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge Fabric into PROD
        uses: peter-evans/merge-renovate-branch@v2
        with:
          branch-name: fabric
          target-branch: PROD
          commit-message: "Merge 'fabric' into 'PROD' [skip ci]"
          delete-branch: false
