name: Merge Fabric into PROD

on:
  push:
    branches:
      - fabric
permissions:
  contents: write  # Grant write permissions to GITHUB_TOKEN
  
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PROD Branch
        uses: actions/checkout@v3
        with:
          ref: PROD
          fetch-depth: 0

      - name: Set Up Git Config
        run: |
          git config --global user.name 'aassou'
          git config --global user.email 'ayoubaassou01@gmail.com'

      - name: Fetch Fabric Branch
        run: git fetch origin fabric

      - name: Merge Fabric into PROD Without YAML File
        run: |
          # Merge without committing
          git merge origin/fabric --no-commit --no-ff
          
          # Remove the YAML file from the merge
          git rm --cached .github/workflows/merge-fabric-to-prod.yml || true
          
          # Commit the merge
          git commit -m "Merge 'fabric' into 'PROD' [skip ci]"

      - name: Push Changes to PROD
        run: git push origin PROD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
